<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GuiaPractica1</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Main.cs" />
    <Compile Include="Ejercicio*/**/*.cs" Exclude="Ejercicio*/Program.cs;Ejercicio*/**/obj/**;Ejercicio*/**/bin/**" />
  </ItemGroup>

</Project>